"""SQLAlchemy ORM models for raw tickets, processed tickets, and embeddings."""

import uuid
from datetime import datetime, timezone

from pgvector.sqlalchemy import Vector
from sqlalchemy import DateTime, Float, ForeignKey, String, Text, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class RawTicket(Base):
    """Source-of-truth table for ingested ticket data.

    Contains only customer-submitted information. Never mutated by LLM pipeline.
    """

    __tablename__ = "raw_tickets"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    customer_email: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="open")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    last_updated: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # One-to-one relationship to processed output
    processed_ticket: Mapped["ProcessedTicket | None"] = relationship(
        back_populates="raw_ticket", uselist=False, cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<RawTicket {self.id} status={self.status}>"


class ProcessedTicket(Base):
    """LLM-enriched output table.

    Contains sentiment analysis, tags, and demographics generated by the LLM.
    Linked to a RawTicket via raw_ticket_id. Safe to delete and re-process.
    """

    __tablename__ = "processed_tickets"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    raw_ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("raw_tickets.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
    )
    sentiment: Mapped[str | None] = mapped_column(String(20), nullable=True)
    emotional_tone: Mapped[str | None] = mapped_column(String(20), nullable=True)
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    tags: Mapped[dict | None] = mapped_column(JSONB, nullable=True, default=None)
    demographics: Mapped[dict | None] = mapped_column(JSONB, nullable=True, default=None)
    processed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    last_updated: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    raw_ticket: Mapped["RawTicket"] = relationship(back_populates="processed_ticket")
    embedding: Mapped["TicketEmbedding | None"] = relationship(
        back_populates="processed_ticket", uselist=False, cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<ProcessedTicket {self.id} raw_ticket_id={self.raw_ticket_id}>"


class TicketEmbedding(Base):
    """Vector embedding for semantic search, linked to processed ticket."""

    __tablename__ = "ticket_embeddings"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("processed_tickets.id", ondelete="CASCADE"),
        primary_key=True,
    )
    embedding = mapped_column(Vector(1536), nullable=False)

    processed_ticket: Mapped["ProcessedTicket"] = relationship(back_populates="embedding")

    def __repr__(self) -> str:
        return f"<TicketEmbedding processed_ticket_id={self.id}>"
