import type { Ticket } from "./types"

export const mockTickets: Ticket[] = [
  {
    id: "a1b2c3d4-0001-4a5b-8c9d-000000000001",
    title: "Ingestion failure with Daylight capture extension",
    content: "Good afternoon\n\nI've been getting \"ingestion failure\" when trying to use the Daylight capture extension. How do I fix it?",
    tags: [{ category: "sentiment", value: "neutral" }, { category: "emotional_tone", value: "neutral" }, { category: "topics", value: "product" }, { category: "priority", value: "normal" }],
    demographics: null,
    sentiment: "neutral",
    emotional_tone: "neutral",
    confidence: 0.92,
    customer_name: "Alex Rivera",
    customer_email: "alex.rivera@example.com",
    is_vip: false,
    status: "open",
    created_at: "2026-02-13T09:00:00Z",
    last_updated: "2026-02-13T09:00:00Z",
  },
  {
    id: "a1b2c3d4-0002-4a5b-8c9d-000000000002",
    title: "Order status update request",
    content: "Hello,\n\nI placed an order and looking for an update. Thank you ORDER #JAGAR-112361649",
    tags: [{ category: "sentiment", value: "neutral" }, { category: "emotional_tone", value: "neutral" }, { category: "topics", value: "shipping" }, { category: "priority", value: "normal" }],
    demographics: null,
    sentiment: "neutral",
    emotional_tone: "neutral",
    confidence: 0.88,
    customer_name: "Morgan Lee",
    customer_email: "morgan.lee@example.com",
    is_vip: false,
    status: "open",
    created_at: "2026-02-13T08:30:00Z",
    last_updated: "2026-02-13T08:30:00Z",
  },
  {
    id: "a1b2c3d4-0003-4a5b-8c9d-000000000003",
    title: "Return request — love the device but incompatible software",
    content: "Hi,\n\nI recently received my daylight computer and while I love the device, I realized I won't be able to use it with the software I'd need. I'd like to return it since I'm within the 30 days. It has no wear or signs of use whatsoever. Order number-112412749.",
    tags: [{ category: "sentiment", value: "positive" }, { category: "emotional_tone", value: "delighted" }, { category: "topics", value: "returns" }, { category: "priority", value: "normal" }],
    demographics: null,
    sentiment: "positive",
    emotional_tone: "delighted",
    confidence: 0.95,
    customer_name: "Taylor Kim",
    customer_email: "taylor.kim@example.com",
    is_vip: false,
    status: "open",
    created_at: "2026-02-12T14:20:00Z",
    last_updated: "2026-02-12T14:20:00Z",
  },
  {
    id: "a1b2c3d4-0004-4a5b-8c9d-000000000004",
    title: "Reader app feedback — delete, rename, folders",
    content: "Hello,\n\nI LOVE the reader app, but I wanted to give some feedback because I'd love to have more functionality with organization of files. Is there a way to delete files from the reader? I only see a way to archive them.\n\nAlso, I've added a couple files via the Daylight Capture app that show up in the Reader as Untitled. Is there a way to rename them?\n\nAnd lastly, it would be amazing to be able to make different folders to organize different types of material.\n\nThanks so much!",
    tags: [{ category: "sentiment", value: "positive" }, { category: "emotional_tone", value: "delighted" }, { category: "topics", value: "product" }, { category: "topics", value: "feature-request" }, { category: "priority", value: "normal" }],
    demographics: null,
    sentiment: "positive",
    emotional_tone: "delighted",
    confidence: 0.94,
    customer_name: "Jordan Patel",
    customer_email: "jordan.patel@example.com",
    is_vip: true,
    status: "in_progress",
    created_at: "2026-02-12T11:00:00Z",
    last_updated: "2026-02-13T10:00:00Z",
  },
  {
    id: "a1b2c3d4-0005-4a5b-8c9d-000000000005",
    title: "DC-1 login loop with 2FA passkey",
    content: "Hi, I recently tried to use my DC-1 after a while. It asked me to log into my google account, which is protected by a 2fa passkey in my icloud account. When I try to use it I get stuck in a loop. How can I fix this? The DC-1 is pretty much useless if I can't log in.",
    tags: [{ category: "sentiment", value: "negative" }, { category: "emotional_tone", value: "frustrated" }, { category: "topics", value: "product" }, { category: "priority", value: "high" }],
    demographics: null,
    sentiment: "negative",
    emotional_tone: "frustrated",
    confidence: 0.90,
    customer_name: "Casey Nguyen",
    customer_email: "casey.nguyen@example.com",
    is_vip: false,
    status: "open",
    created_at: "2026-02-12T09:15:00Z",
    last_updated: "2026-02-12T09:15:00Z",
  },
  {
    id: "a1b2c3d4-0006-4a5b-8c9d-000000000006",
    title: "Kid Daylight — capabilities and ads question",
    content: "Hello,\n\nI purchased a daylight computer for my son during the Amber Light sale and not only is he happy with it, his younger brother is keen to have one as well.\n\nI see that you have released a daylight computer for 8-14 year olds. My 12 year old is concerned that the kid specific daylight will not be able to do everything that the regular one can.\n\nAlso, the ads that pop up on my son's daylight are annoying. Is there an easy way to disable them?",
    tags: [{ category: "sentiment", value: "positive" }, { category: "emotional_tone", value: "happy" }, { category: "topics", value: "product" }, { category: "topics", value: "feature-request" }, { category: "priority", value: "normal" }],
    demographics: { family_status: { value: "has kids ages ~12 and younger", confidence: 0.9 } },
    sentiment: "positive",
    emotional_tone: "happy",
    confidence: 0.91,
    customer_name: "Sam Whitfield",
    customer_email: "sam.whitfield@example.com",
    is_vip: true,
    status: "in_progress",
    created_at: "2026-02-11T16:00:00Z",
    last_updated: "2026-02-12T14:00:00Z",
  },
  {
    id: "a1b2c3d4-0007-4a5b-8c9d-000000000007",
    title: "ESA purchase for Arizona students",
    content: "Hi there!\n\nI have two Arizona ESA students I'd like to purchase tablets for. Can you let me know how to use the funds to purchase?\n\nThank you so much!",
    tags: [{ category: "sentiment", value: "neutral" }, { category: "emotional_tone", value: "neutral" }, { category: "topics", value: "billing" }, { category: "priority", value: "normal" }],
    demographics: { location: { value: "Arizona", confidence: 0.85 } },
    sentiment: "neutral",
    emotional_tone: "neutral",
    confidence: 0.87,
    customer_name: "Robin Vasquez",
    customer_email: "robin.vasquez@example.com",
    is_vip: false,
    status: "closed",
    created_at: "2026-01-15T12:00:00Z",
    last_updated: "2026-01-16T18:00:00Z",
  },
  {
    id: "a1b2c3d4-0008-4a5b-8c9d-000000000008",
    title: "Shipment stuck in Pennsylvania — angry customer",
    content: "Good morning\n\nI am emailing regarding the above order #. My shipment seems to be stuck in Pennsylvania for the last several days. Can you check on the status of my order and when I should expect my shipment?\n\nMy package was supposed to be delivered Friday — before the storm.",
    tags: [{ category: "sentiment", value: "negative" }, { category: "emotional_tone", value: "angry" }, { category: "topics", value: "shipping" }, { category: "priority", value: "urgent" }],
    demographics: null,
    sentiment: "negative",
    emotional_tone: "angry",
    confidence: 0.96,
    customer_name: "Dana Kowalski",
    customer_email: "dana.kowalski@example.com",
    is_vip: true,
    status: "in_progress",
    created_at: "2026-01-26T14:00:00Z",
    last_updated: "2026-02-03T10:00:00Z",
  },
  {
    id: "a1b2c3d4-0009-4a5b-8c9d-000000000009",
    title: "Screen frozen — warranty inquiry",
    content: "Hi I ordered a computer last year and my screen is frozen and won't work anymore. I love the computer and am super sad about this. Is there a warranty and do you replace if the computer malfunctions?\n\nOrder number was jagar-111322049",
    tags: [{ category: "sentiment", value: "positive" }, { category: "emotional_tone", value: "happy" }, { category: "topics", value: "product" }, { category: "topics", value: "warranty" }, { category: "priority", value: "high" }],
    demographics: null,
    sentiment: "positive",
    emotional_tone: "happy",
    confidence: 0.93,
    customer_name: "Avery Chen",
    customer_email: "avery.chen@example.com",
    is_vip: false,
    status: "open",
    created_at: "2026-02-10T11:00:00Z",
    last_updated: "2026-02-10T11:00:00Z",
  },
  {
    id: "a1b2c3d4-0010-4a5b-8c9d-000000000010",
    title: "Feature request — phones, laptops, desktop screens",
    content: "Greetings!\n\nI am wondering if you plan to introduce other devices. Phones? Laptops? Desktop screens? I think all would be excellent ideas.\n\nThank you for your time and Happy Holiday Season to all of you and yours!",
    tags: [{ category: "sentiment", value: "positive" }, { category: "emotional_tone", value: "delighted" }, { category: "topics", value: "feature-request" }, { category: "priority", value: "low" }],
    demographics: null,
    sentiment: "positive",
    emotional_tone: "delighted",
    confidence: 0.95,
    customer_name: "Quinn Torres",
    customer_email: "quinn.torres@example.com",
    is_vip: false,
    status: "closed",
    created_at: "2025-12-20T09:00:00Z",
    last_updated: "2025-12-20T09:00:00Z",
  },
  {
    id: "a1b2c3d4-0011-4a5b-8c9d-000000000011",
    title: "Affiliate program inquiry — YouTube channel",
    content: "Hi Daylight Team,\n\nI tend to be a night owl, so I spend more time than I'd like wrapping up work in the evening. I learned about Daylight while researching blue light-minimizing tech for my own use case, but I think your product would be perfect for my audience as well.\n\nI've got a ~15k YouTube channel generating several million dollars in affiliate revenue annually from strategic product reviews. My audience is health-conscious tech enthusiasts aged 25-45.\n\nWould I be welcome to participate in your affiliate program?",
    tags: [{ category: "sentiment", value: "neutral" }, { category: "emotional_tone", value: "neutral" }, { category: "topics", value: "company" }, { category: "priority", value: "normal" }],
    demographics: { occupation: { value: "content creator / YouTuber", confidence: 0.95 }, age_bracket: { value: "25-45", confidence: 0.7 } },
    sentiment: "neutral",
    emotional_tone: "neutral",
    confidence: 0.89,
    customer_name: "Jason Briggs",
    customer_email: "jason@example.com",
    is_vip: false,
    status: "closed",
    created_at: "2026-01-15T16:00:00Z",
    last_updated: "2026-01-16T12:00:00Z",
  },
  {
    id: "a1b2c3d4-0012-4a5b-8c9d-000000000012",
    title: "Accessories — cover and other products",
    content: "Hi,\n\nI purchased one of the Daylight Computers and was wondering where I can purchase the cover for it. Are there any other accessories available for it?\n\nThank you.",
    tags: [{ category: "sentiment", value: "neutral" }, { category: "emotional_tone", value: "neutral" }, { category: "topics", value: "accessories" }, { category: "priority", value: "normal" }],
    demographics: null,
    sentiment: "neutral",
    emotional_tone: "neutral",
    confidence: 0.90,
    customer_name: "Reese Park",
    customer_email: "reese.park@example.com",
    is_vip: false,
    status: "closed",
    created_at: "2026-02-08T10:00:00Z",
    last_updated: "2026-02-08T14:00:00Z",
  },
  {
    id: "a1b2c3d4-0013-4a5b-8c9d-000000000013",
    title: "Homeschool family — product interest and job inquiry",
    content: "Good Afternoon,\n\nI just found your company and was looking over your website. I love the idea of a blue light free computer. I'm in a place now where I'm looking to reduce the noise in my life and the lives of my children. As a homeschool family we are extremely mindful of screen time and prioritize outdoor play and physical books.\n\nI have a Bachelors of Science in Elementary Education and a Masters of Business Administration. Please keep me in mind for any opportunity.",
    tags: [{ category: "sentiment", value: "positive" }, { category: "emotional_tone", value: "delighted" }, { category: "topics", value: "product" }, { category: "topics", value: "company" }, { category: "priority", value: "low" }],
    demographics: { family_status: { value: "homeschool family with children", confidence: 0.92 }, occupation: { value: "education, program management", confidence: 0.88 } },
    sentiment: "positive",
    emotional_tone: "delighted",
    confidence: 0.91,
    customer_name: "Jan Morales",
    customer_email: "jan.morales@example.com",
    is_vip: false,
    status: "closed",
    created_at: "2025-12-18T14:00:00Z",
    last_updated: "2025-12-18T14:00:00Z",
  },
  {
    id: "a1b2c3d4-0014-4a5b-8c9d-000000000014",
    title: "Billing portal 403 error after upgrade",
    content: "After upgrading to the Enterprise plan, I can no longer access the billing portal. The page returns a 403 error. I've tried clearing cache and using a different browser but the issue persists.",
    tags: [{ category: "sentiment", value: "negative" }, { category: "emotional_tone", value: "frustrated" }, { category: "topics", value: "billing" }, { category: "topics", value: "product" }, { category: "priority", value: "urgent" }],
    demographics: null,
    sentiment: "negative",
    emotional_tone: "frustrated",
    confidence: 0.94,
    customer_name: "Sarah Chen",
    customer_email: "sarah.chen@acmecorp.io",
    is_vip: true,
    status: "open",
    created_at: "2026-02-13T09:15:00Z",
    last_updated: "2026-02-13T09:15:00Z",
  },
  {
    id: "a1b2c3d4-0015-4a5b-8c9d-000000000015",
    title: "Delayed shipping — two weeks and no package",
    content: "Hi there, I ordered my Daylight computer over two weeks ago and it still hasn't arrived. The tracking number hasn't updated in days. I'm very frustrated. Can someone look into this?",
    tags: [{ category: "sentiment", value: "negative" }, { category: "emotional_tone", value: "frustrated" }, { category: "topics", value: "shipping" }, { category: "priority", value: "high" }],
    demographics: null,
    sentiment: "negative",
    emotional_tone: "frustrated",
    confidence: 0.91,
    customer_name: "Ellis Monroe",
    customer_email: "ellis.monroe@example.com",
    is_vip: false,
    status: "open",
    created_at: "2026-02-11T08:00:00Z",
    last_updated: "2026-02-11T08:00:00Z",
  },
]
